name:                hasm
version:             0.1.0.0
github:              "mesabloo/hasm"
license:             MIT
author:              "Mesabloo"
copyright:           "2019 Mesabloo"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mesabloo/hasm#readme>

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -Wall
  - -Wno-name-shadowing

dependencies:
- base
- megaparsec
- template-haskell
- vector
- binary
- mtl
- containers
- bytestring
- lens
- cond

when:
- condition: os(windows)
  then:
    dependencies:
    - Win32

    include-dirs:
    - src/System/MMap

    c-sources:
    - src/System/Mmap/*.c
  else:
    dependencies:
    - unix

tests:
  parsing:
    main:         Main.hs
    source-dirs:  test/Parsing
    dependencies:
    - hasm
    - hspec
  runtime:
    dependencies:
    - hasm
    - hspec
    main:        Main.hs
    when:
    - condition: arch(i386)
      source-dirs: test/Runtime/X86
    - condition: arch(x86_64)
      source-dirs: test/Runtime/X86
    - condition: ! arch(i386) && ! arch(x86_64)
      source-dirs: test/Runtime/Unsupported