name:                hasm
version:             0.1.0.0
github:              "mesabloo/hasm"
license:             MIT
author:              "Mesabloo"
copyright:           "2019 Mesabloo"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mesabloo/hasm#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- template-haskell
- vector
- binary
- mtl
- containers
- bytestring
- lens

library:
  source-dirs: src

tests:
  registers:
    main:        Register.hs
    source-dirs: test
    dependencies:
    - hasm
# tests:
#   hasm-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - hasm
